<a href="https://colab.research.google.com/github/ukhyun-lee/stock_market_analysis/blob/main/%EC%A4%91%EA%B8%89/18%EC%9D%BC%EC%B0%A8_%EC%8B%A4%EC%8A%B51.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [74]:
import pandas as pd

In [75]:
users = pd.read_csv('sample_data/users.dat', sep='::', header=None, engine='python')

In [76]:
users

         0  1   2   3      4
0        1  F   1  10  48067
1        2  M  56  16  70072
2        3  M  25  15  55117
3        4  M  45   7  02460
4        5  M  25  20  55455
...    ... ..  ..  ..    ...
6035  6036  F  25  15  32603
6036  6037  F  45   1  76006
6037  6038  F  56   1  14706
6038  6039  F  45   0  01060
6039  6040  M  25   6  11106

[6040 rows x 5 columns]

In [77]:
users.rename(columns={0:'UserID', 1:'Gender', 2:'Age', 3:'Occupation', 4:'zip-code'}, inplace=True)

In [78]:
age = {
    1:  "Under 18",
    18:  "18-24",
    25:  "25-34",
    35:  "35-44",
    45:  "45-49",
    50:  "50-55",
    56:  "56+"
}

In [79]:
occupation = {
   0:  "other",
	 1:  "academic/educator",
	 2:  "artist",
	 3:  "clerical/admin",
	 4:  "college/grad student",
	 5:  "customer service",
	 6:  "doctor/health care",
	 7:  "executive/managerial",
	 8:  "farmer",
	 9:  "homemaker",
	10:  "K-12 student",
	11:  "lawyer",
	12:  "programmer",
	13:  "retired",
	14:  "sales/marketing",
	15:  "scientist",
	16:  "self-employed",
	17:  "technician/engineer",
	18:  "tradesman/craftsman",
	19:  "unemployed",
	20:  "writer"
}

In [80]:
users.Occupation.map(occupation)
users.Occupation.replace(occupation)

0               K-12 student
1              self-employed
2                  scientist
3       executive/managerial
4                     writer
                ...
6035               scientist
6036       academic/educator
6037       academic/educator
6038                   other
6039      doctor/health care
Name: Occupation, Length: 6040, dtype: object

In [81]:
users['Occupation'] = users.Occupation.map(occupation)

In [82]:
users.Age.map(age)
users.Age.replace(age)

0       Under 18
1            56+
2          25-34
3          45-49
4          25-34
          ...
6035       25-34
6036       45-49
6037         56+
6038       45-49
6039       25-34
Name: Age, Length: 6040, dtype: object

In [83]:
users['Age'] = users.Age.map(age)

In [84]:
users

      UserID Gender       Age            Occupation zip-code
0          1      F  Under 18          K-12 student    48067
1          2      M       56+         self-employed    70072
2          3      M     25-34             scientist    55117
3          4      M     45-49  executive/managerial    02460
4          5      M     25-34                writer    55455
...      ...    ...       ...                   ...      ...
6035    6036      F     25-34             scientist    32603
6036    6037      F     45-49     academic/educator    76006
6037    6038      F       56+     academic/educator    14706
6038    6039      F     45-49                 other    01060
6039    6040      M     25-34    doctor/health care    11106

[6040 rows x 5 columns]

In [85]:
movies = pd.read_csv('sample_data/movies.dat', delimiter='::', encoding='latin1', engine='python',header=None)

In [86]:
movies

         0                                   1                             2
0        1                    Toy Story (1995)   Animation|Children's|Comedy
1        2                      Jumanji (1995)  Adventure|Children's|Fantasy
2        3             Grumpier Old Men (1995)                Comedy|Romance
3        4            Waiting to Exhale (1995)                  Comedy|Drama
4        5  Father of the Bride Part II (1995)                        Comedy
...    ...                                 ...                           ...
3878  3948             Meet the Parents (2000)                        Comedy
3879  3949          Requiem for a Dream (2000)                         Drama
3880  3950                    Tigerland (2000)                         Drama
3881  3951             Two Family House (2000)                         Drama
3882  3952               Contender, The (2000)                Drama|Thriller

[3883 rows x 3 columns]

In [87]:
movies.rename(columns={0:"MovieID", 1:"Title", 2:"Genres"}, inplace=True)

In [88]:
movies

,MovieID,Title,Genres
0,1,Toy Story (1995),Animation|Children's|Comedy
1,2,Jumanji (1995),Adventure|Children's|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
3878,3948,Meet the Parents (2000),Comedy
3879,3949,Requiem for a Dream (2000),Drama
3880,3950,Tigerland (2000),Drama
3881,3951,Two Family House (2000),Drama
3882,3952,"Contender, The (2000)",Drama|Thriller

In [89]:
movies['Year'] = movies.Title.str[-5:-1]

In [90]:
movies

,MovieID,Title,Genres,Year
0,1,Toy Story (1995),Animation|Children's|Comedy,1995
1,2,Jumanji (1995),Adventure|Children's|Fantasy,1995
2,3,Grumpier Old Men (1995),Comedy|Romance,1995
3,4,Waiting to Exhale (1995),Comedy|Drama,1995
4,5,Father of the Bride Part II (1995),Comedy,1995
...,...,...,...,...
3878,3948,Meet the Parents (2000),Comedy,2000
3879,3949,Requiem for a Dream (2000),Drama,2000
3880,3950,Tigerland (2000),Drama,2000
3881,3951,Two Family House (2000),Drama,2000
3882,3952,"Contender, The (2000)",Drama|Thriller,2000

In [91]:
#movies.Title.str.extract('(\d+)')  #regular expression

         0
0     1995
1     1995
2     1995
3     1995
4     1995
...    ...
3878  2000
3879  2000
3880  2000
3881  2000
3882  2000

[3883 rows x 1 columns]

In [92]:
#movies.Title.str.split('(', expand=True)[1].str.split(')', expand=True)[0]

In [93]:
movies['Title'] = movies.Title.str[:-6]

In [94]:
movies['Year'] = movies['Year'].astype('int64')

In [95]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3883 entries, 0 to 3882
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   MovieID  3883 non-null   int64
 1   Title    3883 non-null   object
 2   Genres   3883 non-null   object
 3   Year     3883 non-null   int64
dtypes: int64(2), object(2)
memory usage: 121.5+ KB

In [96]:
ratings = pd.read_csv('sample_data/ratings.dat', delimiter='::', engine='python',header=None)

In [97]:
ratings

            0     1  2          3
0           1  1193  5  978300760
1           1   661  3  978302109
2           1   914  3  978301968
3           1  3408  4  978300275
4           1  2355  5  978824291
...       ...   ... ..        ...
1000204  6040  1091  1  956716541
1000205  6040  1094  5  956704887
1000206  6040   562  5  956704746
1000207  6040  1096  4  956715648
1000208  6040  1097  4  956715569

[1000209 rows x 4 columns]

In [98]:
ratings.rename(columns={0:'UserID', 1:'MovieID', 2:'Rating', 3:'Timestamp'}, inplace=True)

In [99]:
ratings.iloc[0,3]

978300760

In [100]:
import time

In [101]:
time.time()

1690693357.3129025

In [102]:
import datetime

In [103]:
#datetime.datetime.fromtimestamp(ratings.iloc[0,3])
datetime.datetime.fromtimestamp(time.time()).strftime('%Y-%m-%d')

'2023-07-30'

In [104]:
datetime.datetime.utcfromtimestamp(ratings.iloc[0,3])

datetime.datetime(2000, 12, 31, 22, 12, 40)

In [105]:
ratings

         UserID  MovieID  Rating  Timestamp
0             1     1193       5  978300760
1             1      661       3  978302109
2             1      914       3  978301968
3             1     3408       4  978300275
4             1     2355       5  978824291
...         ...      ...     ...        ...
1000204    6040     1091       1  956716541
1000205    6040     1094       5  956704887
1000206    6040      562       5  956704746
1000207    6040     1096       4  956715648
1000208    6040     1097       4  956715569

[1000209 rows x 4 columns]

In [106]:
ratings['Timestamp'] = pd.to_datetime(ratings.Timestamp, unit='s')

In [107]:
ratings

         UserID  MovieID  Rating           Timestamp
0             1     1193       5 2000-12-31 22:12:40
1             1      661       3 2000-12-31 22:35:09
2             1      914       3 2000-12-31 22:32:48
3             1     3408       4 2000-12-31 22:04:35
4             1     2355       5 2001-01-06 23:38:11
...         ...      ...     ...                 ...
1000204    6040     1091       1 2000-04-26 02:35:41
1000205    6040     1094       5 2000-04-25 23:21:27
1000206    6040      562       5 2000-04-25 23:19:06
1000207    6040     1096       4 2000-04-26 02:20:48
1000208    6040     1097       4 2000-04-26 02:19:29

[1000209 rows x 4 columns]

In [108]:
data = ratings.merge(users).merge(movies)

In [73]:
#join (merge보다 한단계 확정된것)

In [58]:
aa = pd.DataFrame({'key':[1,2,3], 'name':['a','b','c']})
bb = pd.DataFrame({'key':[2,3,4,5], 'age':[15,16,20,42]})

In [59]:
aa

   key name
0    1    a
1    2    b
2    3    c

In [60]:
bb

   key  age
0    2   15
1    3   16
2    4   20
3    5   42

In [61]:
aa.join(bb, lsuffix='xxxxxx', how='left')

   keyxxxxxx name  key  age
0          1    a    2   15
1          2    b    3   16
2          3    c    4   20

In [62]:
aa.join(bb, lsuffix='xxxxxx', how='right')

   keyxxxxxx name  key  age
0        1.0    a    2   15
1        2.0    b    3   16
2        3.0    c    4   20
3        NaN  NaN    5   42

In [63]:
aa.join(bb, lsuffix='xxxxxx', how='outer')

   keyxxxxxx name  key  age
0        1.0    a    2   15
1        2.0    b    3   16
2        3.0    c    4   20
3        NaN  NaN    5   42

In [64]:
aa.join(bb, lsuffix='xxxxxx', how='inner')

   keyxxxxxx name  key  age
0          1    a    2   15
1          2    b    3   16
2          3    c    4   20

In [65]:
aa.join(bb, lsuffix='xxxxxx', how='cross')

    keyxxxxxx name  key  age
0           1    a    2   15
1           1    a    3   16
2           1    a    4   20
3           1    a    5   42
4           2    b    2   15
5           2    b    3   16
6           2    b    4   20
7           2    b    5   42
8           3    c    2   15
9           3    c    3   16
10          3    c    4   20
11          3    c    5   42

In [ ]:
# 'left', 'right', 'outer', 'inner', 'cross'

In [66]:
aa.merge(bb, how='left')

   key name   age
0    1    a   NaN
1    2    b  15.0
2    3    c  16.0

In [67]:
aa.merge(bb, how='right')

   key name  age
0    2    b   15
1    3    c   16
2    4  NaN   20
3    5  NaN   42

In [68]:
aa.merge(bb, how='outer')

   key name   age
0    1    a   NaN
1    2    b  15.0
2    3    c  16.0
3    4  NaN  20.0
4    5  NaN  42.0

In [69]:
aa.merge(bb, how='inner')

   key name  age
0    2    b   15
1    3    c   16

In [70]:
aa.merge(bb, how='cross')

    key_x name  key_y  age
0       1    a      2   15
1       1    a      3   16
2       1    a      4   20
3       1    a      5   42
4       2    b      2   15
5       2    b      3   16
6       2    b      4   20
7       2    b      5   42
8       3    c      2   15
9       3    c      3   16
10      3    c      4   20
11      3    c      5   42

In [71]:
pd.concat([aa,bb], axis=0)

   key name   age
0    1    a   NaN
1    2    b   NaN
2    3    c   NaN
0    2  NaN  15.0
1    3  NaN  16.0
2    4  NaN  20.0
3    5  NaN  42.0

In [72]:
pd.concat([aa,bb], axis=1)

   key name  key  age
0  1.0    a    2   15
1  2.0    b    3   16
2  3.0    c    4   20
3  NaN  NaN    5   42

In [109]:
ratings.join(users, lsuffix='xxxxxxx', how='right')

,UserIDxxxxxxx,MovieID,Rating,Timestamp,UserID,Gender,Age,Occupation,zip-code
0,1,1193,5,2000-12-31 22:12:40,1,F,Under 18,K-12 student,48067
1,1,661,3,2000-12-31 22:35:09,2,M,56+,self-employed,70072
2,1,914,3,2000-12-31 22:32:48,3,M,25-34,scientist,55117
3,1,3408,4,2000-12-31 22:04:35,4,M,45-49,executive/managerial,02460
4,1,2355,5,2001-01-06 23:38:11,5,M,25-34,writer,55455
...,...,...,...,...,...,...,...,...,...
6035,44,2174,4,2000-12-28 16:07:21,6036,F,25-34,scientist,32603
6036,44,912,3,2001-10-30 03:18:20,6037,F,45-49,academic/educator,76006
6037,44,1374,4,2000-12-28 22:00:01,6038,F,56+,academic/educator,14706
6038,44,3623,3,2001-10-30 02:47:27,6039,F,45-49,other,01060
6039,44,919,5,2000-12-28 15:59:08,6040,M,25-34,doctor/health care,11106

In [52]:
data

,UserID,MovieID,Rating,Timestamp,Gender,Age,Occupation,zip-code,Title,Genres,Year
0,1,1193,5,2000-12-31 22:12:40,F,Under 18,K-12 student,48067,One Flew Over the Cuckoo's Nest,Drama,1975
1,2,1193,5,2000-12-31 21:33:33,M,56+,self-employed,70072,One Flew Over the Cuckoo's Nest,Drama,1975
2,12,1193,4,2000-12-30 23:49:39,M,25-34,programmer,32793,One Flew Over the Cuckoo's Nest,Drama,1975
3,15,1193,4,2000-12-30 18:01:19,M,25-34,executive/managerial,22903,One Flew Over the Cuckoo's Nest,Drama,1975
4,17,1193,5,2000-12-30 06:41:11,M,50-55,academic/educator,95350,One Flew Over the Cuckoo's Nest,Drama,1975
...,...,...,...,...,...,...,...,...,...,...,...
1000204,5949,2198,5,2000-05-20 18:13:21,M,18-24,technician/engineer,47901,Modulations,Documentary,1998
1000205,5675,2703,3,2000-12-05 15:11:56,M,35-44,sales/marketing,30030,Broken Vessels,Drama,1998
1000206,5780,2845,1,2000-05-12 17:37:48,M,18-24,technician/engineer,92886,White Boys,Drama,1999
1000207,5851,3607,5,2000-05-08 03:30:08,F,18-24,writer,55410,One Little Indian,Comedy|Drama|Western,1973
1000208,5938,2909,4,2000-05-02 13:15:53,M,25-34,academic/educator,35401,"Five Wives, Three Secretaries and Me",Documentary,1998

In [ ]:
#pivot vs pivot-table

In [111]:
xx = pd.DataFrame({'x' : [1,2,3,1,5], 'y' : [2,3,4,5,6], 'z' : [1,3,2,3,4]})

In [112]:
xx

   x  y  z
0  1  2  1
1  2  3  3
2  3  4  2
3  1  5  3
4  5  6  4

In [113]:
xx.pivot(index='x', columns='y', values='z')

y    2    3    4    5    6
x
1  1.0  NaN  NaN  3.0  NaN
2  NaN  3.0  NaN  NaN  NaN
3  NaN  NaN  2.0  NaN  NaN
5  NaN  NaN  NaN  NaN  4.0

In [115]:
xx.set_index( ['x','y'] )

     z
x y
1 2  1
2 3  3
3 4  2
1 5  3
5 6  4

In [116]:
xx.set_index( ['x','y'] ).unstack()

     z
y    2    3    4    5    6
x
1  1.0  NaN  NaN  3.0  NaN
2  NaN  3.0  NaN  NaN  NaN
3  NaN  NaN  2.0  NaN  NaN
5  NaN  NaN  NaN  NaN  4.0

In [117]:
yy = pd.DataFrame({'x' : [1,2,3,1,5], 'y' : [2,3,2,2,6], 'z' : [1,3,2,3,4]})

In [ ]:
yy.pivot(index='x', columns='y', values='z')# 한칸에 두값이 와 error  pivot_table 두개값의 평균으로

In [119]:
yy.pivot_table(index='x', columns='y', values='z')

y    2    3    6
x
1  2.0  NaN  NaN
2  NaN  3.0  NaN
3  2.0  NaN  NaN
5  NaN  NaN  4.0

In [129]:
s = data.pivot(columns='MovieID', index='UserID',values='Rating' ).fillna(0)

In [130]:
s

MovieID,1,2,3,4,5,6,7,8,9,10,...,3943,3944,3945,3946,3947,3948,3949,3950,3951,3952
UserID,,,,,,,,,,,,,,,,,,,,,
1,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6036,0.0,0.0,0.0,2.0,0.0,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6037,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6038,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6039,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6040,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [123]:
from sklearn.metrics import pairwise_distances

In [133]:
si = pairwise_distances(s, metric='cosine')   # movie끼리 코사인
#si = pairwise_distances(s.T, metric='cosine')   # user끼리 코사인

In [134]:
si.shape

(6040, 6040)

In [136]:
cos_similarity = pd.DataFrame(si, index=s.index, columns=s.index)

##사이킷런은 최적화 판다스는 아님

In [137]:
s.corr()

MovieID,1,2,3,4,5,6,7,8,9,10,...,3943,3944,3945,3946,3947,3948,3949,3950,3951,3952
MovieID,,,,,,,,,,,,,,,,,,,,,
1,1.000000,0.262649,0.146536,0.109375,0.170156,0.168087,0.189333,0.082963,0.045705,0.215653,...,0.039913,0.002483,0.054038,0.018530,-0.007335,0.132009,0.076941,0.050559,-0.002849,0.052121
2,0.262649,1.000000,0.169586,0.111616,0.196561,0.137334,0.193658,0.173878,0.126871,0.302042,...,0.025345,0.004734,0.055814,0.061466,0.047608,0.108027,0.075658,0.060941,0.000489,0.045883
3,0.146536,0.169586,1.000000,0.158659,0.268062,0.095834,0.238816,0.068058,0.100622,0.164252,...,0.007877,0.058906,0.032291,0.059063,0.028135,0.104775,0.050016,0.039715,-0.011203,0.034831
4,0.109375,0.111616,0.158659,1.000000,0.247529,0.071081,0.187311,0.034228,0.042133,0.082035,...,0.037847,0.048747,-0.008854,0.007128,0.011165,0.067022,0.064363,0.008411,0.012596,0.058965
5,0.170156,0.196561,0.268062,0.247529,1.000000,0.075012,0.264749,0.076378,0.116465,0.176002,...,0.002233,0.078781,0.032615,0.023873,-0.002865,0.107924,0.048976,0.033442,-0.005872,0.064648
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3948,0.132009,0.108027,0.104775,0.067022,0.107924,0.112623,0.106178,0.057789,0.052270,0.117866,...,0.152830,0.044625,0.090117,0.181573,0.048989,1.000000,0.275060,0.145673,0.100880,0.303829
3949,0.076941,0.075658,0.050016,0.064363,0.048976,0.130746,0.063735,0.060214,0.075553,0.061091,...,0.225868,0.093686,0.057280,0.139086,0.089883,0.275060,1.000000,0.290993,0.187273,0.310993
3950,0.050559,0.060941,0.039715,0.008411,0.033442,0.087456,0.036632,0.076474,-0.006121,0.068513,...,0.116725,0.209876,0.051354,0.114863,0.088407,0.145673,0.290993,1.000000,0.197081,0.219895
3951,-0.002849,0.000489,-0.011203,0.012596,-0.005872,-0.001102,0.015910,0.064715,-0.009609,-0.011748,...,0.163426,0.129899,0.081032,0.096689,0.008803,0.100880,0.187273,0.197081,1.000000,0.179693
3952,0.052121,0.045883,0.034831,0.058965,0.064648,0.143515,0.078906,0.021379,0.029224,0.077688,...,0.152138,0.053318,0.014192,0.157547,0.103133,0.303829,0.310993,0.219895,0.179693,1.000000

In [138]:
cor_similarity = s.T.corr()

In [ ]:
cor_similarity

# 유사도 측정 방식에 따라 결과가 다름

In [140]:
cos_similarity.loc[1].sort_values(ascending=False)[:10]

UserID
1919    1.0
1566    1.0
4804    1.0
1986    1.0
4851    1.0
158     1.0
1933    1.0
3838    1.0
1888    1.0
1864    1.0
Name: 1, dtype: float64

In [144]:
cos_similarity.loc[1].nlargest(10)

UserID
46     1.0
158    1.0
210    1.0
218    1.0
279    1.0
304    1.0
345    1.0
356    1.0
364    1.0
391    1.0
Name: 1, dtype: float64

In [139]:
cor_similarity.loc[1].sort_values(ascending=False)[1:11]

UserID
1       1.000000
5343    0.405356
5190    0.404446
1481    0.380623
1283    0.379054
5705    0.346293
5762    0.338609
1359    0.338525
1476    0.328919
541     0.319436
1858    0.318789
Name: 1, dtype: float64

In [146]:
cor_similarity.loc[1].nlargest(11)[1:]

UserID
5343    0.405356
5190    0.404446
1481    0.380623
1283    0.379054
5705    0.346293
5762    0.338609
1359    0.338525
1476    0.328919
541     0.319436
1858    0.318789
Name: 1, dtype: float64

In [ ]:
 #1 나하고 가까운 애 함수로 구하는 것

In [193]:

def find_n_similirties_by_user(user_id, n=5):
    return cor_similarity.loc[user_id].nlargest(n+1)[1:].index

In [ ]:
#2 내가 본 영화 빼야

In [194]:

def find_seen_movies_by_user(user_id):
    return data[data['UserID']==user_id].MovieID.values

In [ ]:
#3 몇명이 본 영화 빼야

In [195]:

def find_seen_movies_by_users(user_ids):
    return data[data['UserID'].isin(user_ids)].MovieID.values

In [ ]:
#4 나하고 가까운 애들이 본 영화 빼야

In [196]:

def find_movies_by_user(user_id, n=5):
    users = cor_similarity.loc[user_id].nlargest(n+1)[1:].index
    return data[data['UserID'].isin(users)].MovieID.values

In [ ]:
#5  나하고 가까운 애들이 안본 영화 빼야

In [198]:

def find_unseen_movies_by_user(user_id, n=5):
    others = cor_similarity.loc[user_id].nlargest(n+1)[1:].index
    others_movies = data[data['UserID'].isin(others)].MovieID.values
    mine_movies = data[data['UserID']==user_id].MovieID.values
    movie_index = np.setdiff1d(others_movies, mine_movies)
    return data[data['MovieID'].isin(movie_index)]

In [229]:
mean_rating = ratings.groupby('MovieID', as_index=False)[['MovieID','Rating']].mean()

In [230]:
mean_rating

      MovieID    Rating
0         1.0  4.146846
1         2.0  3.201141
2         3.0  3.016736
3         4.0  2.729412
4         5.0  3.006757
...       ...       ...
3701   3948.0  3.635731
3702   3949.0  4.115132
3703   3950.0  3.666667
3704   3951.0  3.900000
3705   3952.0  3.780928

[3706 rows x 2 columns]

In [231]:
movie_rating = mean_rating.merge(movies)

In [232]:
movie_rating

,MovieID,Rating,Title,Genres,Year
0,1.0,4.146846,Toy Story,Animation|Children's|Comedy,1995
1,2.0,3.201141,Jumanji,Adventure|Children's|Fantasy,1995
2,3.0,3.016736,Grumpier Old Men,Comedy|Romance,1995
3,4.0,2.729412,Waiting to Exhale,Comedy|Drama,1995
4,5.0,3.006757,Father of the Bride Part II,Comedy,1995
...,...,...,...,...,...
3701,3948.0,3.635731,Meet the Parents,Comedy,2000
3702,3949.0,4.115132,Requiem for a Dream,Drama,2000
3703,3950.0,3.666667,Tigerland,Drama,2000
3704,3951.0,3.900000,Two Family House,Drama,2000
3705,3952.0,3.780928,"Contender, The",Drama|Thriller,2000

In [ ]:
#6 나하고 가까운 애들이 안본 영화 중 rank 몇이상 추천

In [200]:

def find_unseen_movies_by_user_rating(user_id, n=5, r=4):
    others = cor_similarity.loc[user_id].nlargest(n+1)[1:].index
    others_movies = data[data['UserID'].isin(others)].MovieID.values
    mine_movies = data[data['UserID']==user_id].MovieID.values
    movie_index = np.setdiff1d(others_movies, mine_movies)
    rating_index = movie_rating[(movie_rating['MovieID'].isin(movie_index)) & (movie_rating['Rating'] >= r)]
    return rating_index

In [233]:
find_unseen_movies_by_user_rating(50, 3)

,MovieID,Rating,Title,Genres,Year
106,110.0,4.234957,Braveheart,Action|Drama|War,1995
575,589.0,4.058513,Terminator 2: Judgment Day,Action|Sci-Fi|Thriller,1991
890,951.0,4.249370,His Girl Friday,Comedy,1940
1018,1090.0,4.090114,Platoon,Drama|War,1986
1107,1197.0,4.303710,"Princess Bride, The",Action|Adventure|Comedy|Romance,1987
1131,1221.0,4.357565,"Godfather: Part II, The",Action|Crime|Drama,1974
1143,1234.0,4.320305,"Sting, The",Comedy|Crime,1973
1156,1248.0,4.215953,Touch of Evil,Crime|Film-Noir|Thriller,1958
1157,1249.0,4.005457,Nikita (La Femme Nikita),Thriller,1990
1167,1259.0,4.096919,Stand by Me,Adventure|Comedy|Drama,1986
1177,1269.0,4.168155,Arsenic and Old Lace,Comedy|Mystery|Thriller,1944
1192,1284.0,4.312384,"Big Sleep, The",Film-Noir|Mystery,1946
1260,1358.0,4.208156,Sling Blade,Drama|Thriller,1996
2755,2966.0,4.055944,"Straight Story, The",Drama,1999

In [237]:
find_unseen_movies_by_user_rating(2)

,MovieID,Rating,Title,Genres,Year
0,1.0,4.146846,Toy Story,Animation|Children's|Comedy,1995
16,17.0,4.027545,Sense and Sensibility,Drama|Romance,1995
46,47.0,4.106420,Seven (Se7en),Crime|Thriller,1995
49,50.0,4.517106,"Usual Suspects, The",Crime|Thriller,1995
56,58.0,4.093812,"Postino, Il (The Postman)",Drama|Romance,1994
...,...,...,...,...,...
3393,3634.0,4.254545,Seven Days in May,Thriller,1964
3429,3671.0,4.047364,Blazing Saddles,Comedy|Western,1974
3441,3683.0,4.218153,Blood Simple,Drama|Film-Noir,1984
3546,3789.0,4.198718,"Pawnbroker, The",Drama,1965
3568,3811.0,4.102778,Breaker Morant,Drama|War,1980

In [235]:
mean_rating = ratings.groupby('MovieID', as_index=False)[['Rating']].mean()

In [236]:
mean_rating

      MovieID    Rating
0           1  4.146846
1           2  3.201141
2           3  3.016736
3           4  2.729412
4           5  3.006757
...       ...       ...
3701     3948  3.635731
3702     3949  4.115132
3703     3950  3.666667
3704     3951  3.900000
3705     3952  3.780928

[3706 rows x 2 columns]

In [171]:
find_movies_by_user(1)

array([ 661,  661,  914, 3408, 2355, 2355, 2355, 2355, 1197, 1197, 1197,
       1287, 2804,  594,  594,  594,  594,  594,  919,  919,  919,  919,
        595,  595,  595,  595,  595, 2918, 2918, 1035, 1035, 2791, 2791,
       2791, 2687, 2687, 2687, 2687, 2018, 2018, 2018, 2797,  720, 1270,
       1270, 1270,  527,  527,  527,   48, 1097, 1097, 1097, 1097, 1097,
       1721, 1721,  745,  745, 2294, 2294, 2294, 1566, 1566,  588,  588,
        588,  588,  588, 1907, 1907, 1907, 1907,  783,  783,  783, 1022,
       1022, 1022, 1022, 2762, 2762,  150,    1,    1,    1,    1,    1,
        260,  260,  260, 1028, 1028, 1028, 1029, 1029, 1029, 1029, 1207,
       2028, 2028, 2028, 2028,  531, 3114, 3114, 3114, 3114, 3114,  608,
        608,  608,  608, 1537,  648, 2628, 1210, 1210, 1213, 3578, 2881,
        902, 1259, 1188,  110,  110, 2858, 2858, 1225, 3699,  480,  480,
        480, 2067, 1265, 1265,  590, 1198,  593,  593,  593,  593, 2571,
       2571, 1917, 2396, 2396,  380,  457,  457,  920, 3418,  780, 1784,
       2006,  318,  356,  356, 3421, 2997, 2167, 1580, 1580, 1049, 1266,
        733, 2470, 2617, 1136, 2081, 2081, 2081, 2081, 2081, 1036, 1387,
       1201, 1240, 2987, 2987,   39,  866, 2770, 2058,   47, 2700, 2700,
        296,  296, 1617, 1617,  377, 2716, 1704, 2291, 2291, 2580, 1649,
       1500, 2959, 1722,  551, 1517, 3260, 2683, 2683,  994,   29, 1095,
         34,   34,   34,   36, 1030,  364,  364, 1043,  597, 2506, 1569,
       3536,  838,  266,  912, 2100, 1573, 1221, 1393, 1393, 1682, 1059,
       1274,  741, 2297, 1735, 3481, 2324, 2699, 3298, 1777, 3301, 1343,
       3160, 1060, 1148, 1148, 3253, 1584, 1223, 3358, 2125, 2054,  587,
          2,    7, 2137, 2137, 2137, 1409,  592,  596,  596,  596, 1345,
       2078, 2078, 2078, 2078, 2080, 2080, 2080, 1282, 1282, 2087, 2087,
       3466, 3034, 2161,  904, 2096, 2096, 2096,  339, 1377,  916,  923,
        784, 1023, 1967,  351, 1031, 1032, 1032, 2424, 2005,  539,  539,
       3175, 2015, 2015, 1073,  543, 3254, 2399, 1230, 1234, 2043, 2045,
        246, 3396,  788,  440,  986,  708, 3785, 2694, 2485, 3005, 2724,
        832, 2763, 1396, 2273, 2394, 2888, 2664,  446, 2455, 1748, 2123,
       2123,  158, 2141, 2141,  168, 2085, 2085, 2085, 2089, 2248, 2248,
       1033,   86, 2020, 1094, 1258, 1407, 1407, 3082, 1994, 2502, 1219,
       3000, 1405, 1405,  910,  910,   11, 3708,  303, 2059,  236,  673,
        673,  252,  195, 1888, 1541,  455,  605,   74, 1593,  207, 3159,
       1680, 1183,  154, 1835, 1895, 3712, 1894,   46, 3157, 2430, 3615,
       1177, 1280, 3285, 1858, 3768, 2899,  709, 2924, 3225, 2048, 1515,
       3715,  917])

In [202]:
set(find_movies_by_user(1)) - set(find_seen_movies_by_user(1))

{2,
 7,
 11,
 29,
 34,
 36,
 39,
 46,
 47,
 74,
 86,
 110,
 154,
 158,
 168,
 195,
 207,
 236,
 246,
 252,
 266,
 296,
 303,
 318,
 339,
 351,
 356,
 364,
 377,
 380,
 440,
 446,
 455,
 457,
 480,
 539,
 543,
 551,
 587,
 590,
 592,
 593,
 596,
 597,
 605,
 648,
 673,
 708,
 709,
 733,
 741,
 780,
 784,
 788,
 832,
 838,
 866,
 902,
 904,
 910,
 912,
 916,
 917,
 920,
 923,
 986,
 994,
 1023,
 1030,
 1031,
 1032,
 1033,
 1036,
 1043,
 1049,
 1059,
 1060,
 1073,
 1094,
 1095,
 1136,
 1148,
 1177,
 1183,
 1188,
 1198,
 1201,
 1210,
 1213,
 1219,
 1221,
 1223,
 1225,
 1230,
 1234,
 1240,
 1258,
 1259,
 1265,
 1266,
 1274,
 1280,
 1282,
 1343,
 1345,
 1377,
 1387,
 1393,
 1396,
 1405,
 1407,
 1409,
 1500,
 1515,
 1517,
 1537,
 1541,
 1569,
 1573,
 1580,
 1584,
 1593,
 1617,
 1649,
 1680,
 1682,
 1704,
 1722,
 1735,
 1748,
 1777,
 1784,
 1835,
 1858,
 1888,
 1894,
 1895,
 1917,
 1967,
 1994,
 2005,
 2006,
 2015,
 2020,
 2043,
 2045,
 2048,
 2054,
 2058,
 2059,
 2067,
 2078,
 2080,
 2081,
 2085,
 2087,
 2089,
 2096,
 2100,
 2123,
 2125,
 2137,
 2141,
 2161,
 2167,
 2248,
 2273,
 2291,
 2297,
 2324,
 2394,
 2396,
 2399,
 2424,
 2430,
 2455,
 2470,
 2485,
 2502,
 2506,
 2571,
 2580,
 2617,
 2628,
 2664,
 2683,
 2694,
 2699,
 2700,
 2716,
 2724,
 2763,
 2770,
 2858,
 2881,
 2888,
 2899,
 2924,
 2959,
 2987,
 2997,
 3000,
 3005,
 3034,
 3082,
 3157,
 3159,
 3160,
 3175,
 3225,
 3253,
 3254,
 3260,
 3285,
 3298,
 3301,
 3358,
 3396,
 3418,
 3421,
 3466,
 3481,
 3536,
 3578,
 3615,
 3699,
 3708,
 3712,
 3715,
 3768,
 3785}

In [204]:
import numpy as np

In [205]:
np.setdiff1d(find_movies_by_user(1), find_seen_movies_by_user(1))

array([   2,    7,   11,   29,   34,   36,   39,   46,   47,   74,   86,
        110,  154,  158,  168,  195,  207,  236,  246,  252,  266,  296,
        303,  318,  339,  351,  356,  364,  377,  380,  440,  446,  455,
        457,  480,  539,  543,  551,  587,  590,  592,  593,  596,  597,
        605,  648,  673,  708,  709,  733,  741,  780,  784,  788,  832,
        838,  866,  902,  904,  910,  912,  916,  917,  920,  923,  986,
        994, 1023, 1030, 1031, 1032, 1033, 1036, 1043, 1049, 1059, 1060,
       1073, 1094, 1095, 1136, 1148, 1177, 1183, 1188, 1198, 1201, 1210,
       1213, 1219, 1221, 1223, 1225, 1230, 1234, 1240, 1258, 1259, 1265,
       1266, 1274, 1280, 1282, 1343, 1345, 1377, 1387, 1393, 1396, 1405,
       1407, 1409, 1500, 1515, 1517, 1537, 1541, 1569, 1573, 1580, 1584,
       1593, 1617, 1649, 1680, 1682, 1704, 1722, 1735, 1748, 1777, 1784,
       1835, 1858, 1888, 1894, 1895, 1917, 1967, 1994, 2005, 2006, 2015,
       2020, 2043, 2045, 2048, 2054, 2058, 2059, 2067, 2078, 2080, 2081,
       2085, 2087, 2089, 2096, 2100, 2123, 2125, 2137, 2141, 2161, 2167,
       2248, 2273, 2291, 2297, 2324, 2394, 2396, 2399, 2424, 2430, 2455,
       2470, 2485, 2502, 2506, 2571, 2580, 2617, 2628, 2664, 2683, 2694,
       2699, 2700, 2716, 2724, 2763, 2770, 2858, 2881, 2888, 2899, 2924,
       2959, 2987, 2997, 3000, 3005, 3034, 3082, 3157, 3159, 3160, 3175,
       3225, 3253, 3254, 3260, 3285, 3298, 3301, 3358, 3396, 3418, 3421,
       3466, 3481, 3536, 3578, 3615, 3699, 3708, 3712, 3715, 3768, 3785])

In [228]:
find_unseen_movies_by_user(4)

,UserID,MovieID,Rating,Timestamp,Gender,Age,Occupation,zip-code,Title,Genres,Year
1725,1,661,3,2000-12-31 22:35:09,F,Under 18,K-12 student,48067,James and the Giant Peach,Animation|Children's|Musical,1996
1726,23,661,2,2001-01-02 18:38:59,M,35-44,other,90049,James and the Giant Peach,Animation|Children's|Musical,1996
1727,49,661,3,2000-12-28 03:05:50,M,18-24,programmer,77084,James and the Giant Peach,Animation|Children's|Musical,1996
1728,53,661,5,2000-12-28 05:02:06,M,25-34,other,96931,James and the Giant Peach,Animation|Children's|Musical,1996
1729,57,661,4,2000-12-27 16:45:11,M,18-24,unemployed,30350,James and the Giant Peach,Animation|Children's|Musical,1996
...,...,...,...,...,...,...,...,...,...,...,...
970850,5568,1604,4,2000-05-26 03:25:24,M,18-24,college/grad student,49841,Money Talks,Action|Comedy,1997
970851,5570,1604,4,2000-05-28 19:26:17,M,25-34,academic/educator,07666,Money Talks,Action|Comedy,1997
970852,5788,1604,1,2000-05-12 05:08:08,M,25-34,other,92646,Money Talks,Action|Comedy,1997
970853,5795,1604,1,2000-05-12 15:27:00,M,25-34,academic/educator,92688,Money Talks,Action|Comedy,1997
970854,5896,1604,1,2000-05-04 16:59:36,M,25-34,other,60657,Money Talks,Action|Comedy,1997

In [207]:
find_seen_movies_by_users(find_n_similirties_by_user(5))

array([1193, 1193, 1193, ..., 3569,  882,  884])

In [150]:
data[data['UserID']==1].MovieID.values

array([1193,  661,  914, 3408, 2355, 1197, 1287, 2804,  594,  919,  595,
        938, 2398, 2918, 1035, 2791, 2687, 2018, 3105, 2797, 2321,  720,
       1270,  527, 2340,   48, 1097, 1721, 1545,  745, 2294, 3186, 1566,
        588, 1907,  783, 1836, 1022, 2762,  150,    1, 1961, 1962, 2692,
        260, 1028, 1029, 1207, 2028,  531, 3114,  608, 1246])

In [ ]:
#여러명이 본 영화를 빼려면

In [ ]:
# 1 or 2

In [ ]:
data[( data['UserID']==1)| (data['UserID']==2)].MovieID.values

In [157]:
data[( data['UserID']==1)| (data['UserID']==2) | (data['UserID']==3)].MovieID.values

array([1193, 1193,  661,  914, 3408, 2355, 2355, 1197, 1197, 1287, 2804,
        594,  919,  595,  938, 2398, 2918, 1035, 2791, 2687, 2018, 3105,
       3105, 2797, 2321, 2321,  720, 1270, 1270,  527, 2340,   48, 1097,
       1721, 1545,  745, 2294, 3186, 1566,  588, 1907,  783, 1836, 1022,
       2762,  150,    1, 1961, 1961, 1962, 1962, 2692,  260,  260, 1028,
       1029, 1207, 1207, 2028, 2028,  531, 3114, 3114,  608, 1246, 1246,
       1357, 3068, 1537,  647, 2194,  648,  648, 2268, 2628, 1103, 2916,
       3468, 1210, 1210, 1792, 1687, 1213, 3578, 2881, 3030, 1217,  434,
       2126, 3107, 3108, 3035, 1253, 1610,  292, 2236, 3071,  902,  368,
       1259, 1259, 3147, 1544, 1293, 1188, 3255, 3256, 3257,  110, 2278,
       2490, 1834, 3471,  589, 1690, 3654, 2852, 1945,  982, 1873, 2858,
       2858, 1225,  515,  442, 2312,  265, 1408, 1084, 3699,  480,  480,
       1442, 2067, 1265, 1265, 1370, 1801, 1372, 2353, 3334, 2427,  590,
        590, 1196, 1196, 1552,  736, 1198, 1198,  593,  593, 2359,   95,
       2717, 2571, 1917, 2396, 3735, 1953, 1597, 3809, 1954, 1955,  235,
       1124, 1957,  163,   21,  165, 1090,  380, 2501,  349,  457, 1096,
        920,  459, 1527, 3418, 1385, 3451, 3095,  780,  498, 2728, 2002,
       1784, 2943, 2006, 2006,  318, 1968, 1968, 3678, 1244,  356, 1245,
       3893, 1247, 3421, 1641, 1394, 3534,  104, 2735, 1431, 3868, 1079,
       2997, 1615, 1291,  653, 2167, 1580, 3619, 1049, 1261,  552, 1266,
        733, 1378, 1379, 3552, 1304, 2470, 3168, 2617, 3671, 2871, 2115,
       1136, 2081])

In [154]:
x = 1

In [155]:
x in (1,2,3)  # or 의 대용

True

In [156]:
data[data['UserID'].isin([1,2,3])].MovieID.values

array([1193, 1193,  661,  914, 3408, 2355, 2355, 1197, 1197, 1287, 2804,
        594,  919,  595,  938, 2398, 2918, 1035, 2791, 2687, 2018, 3105,
       3105, 2797, 2321, 2321,  720, 1270, 1270,  527, 2340,   48, 1097,
       1721, 1545,  745, 2294, 3186, 1566,  588, 1907,  783, 1836, 1022,
       2762,  150,    1, 1961, 1961, 1962, 1962, 2692,  260,  260, 1028,
       1029, 1207, 1207, 2028, 2028,  531, 3114, 3114,  608, 1246, 1246,
       1357, 3068, 1537,  647, 2194,  648,  648, 2268, 2628, 1103, 2916,
       3468, 1210, 1210, 1792, 1687, 1213, 3578, 2881, 3030, 1217,  434,
       2126, 3107, 3108, 3035, 1253, 1610,  292, 2236, 3071,  902,  368,
       1259, 1259, 3147, 1544, 1293, 1188, 3255, 3256, 3257,  110, 2278,
       2490, 1834, 3471,  589, 1690, 3654, 2852, 1945,  982, 1873, 2858,
       2858, 1225,  515,  442, 2312,  265, 1408, 1084, 3699,  480,  480,
       1442, 2067, 1265, 1265, 1370, 1801, 1372, 2353, 3334, 2427,  590,
        590, 1196, 1196, 1552,  736, 1198, 1198,  593,  593, 2359,   95,
       2717, 2571, 1917, 2396, 3735, 1953, 1597, 3809, 1954, 1955,  235,
       1124, 1957,  163,   21,  165, 1090,  380, 2501,  349,  457, 1096,
        920,  459, 1527, 3418, 1385, 3451, 3095,  780,  498, 2728, 2002,
       1784, 2943, 2006, 2006,  318, 1968, 1968, 3678, 1244,  356, 1245,
       3893, 1247, 3421, 1641, 1394, 3534,  104, 2735, 1431, 3868, 1079,
       2997, 1615, 1291,  653, 2167, 1580, 3619, 1049, 1261,  552, 1266,
        733, 1378, 1379, 3552, 1304, 2470, 3168, 2617, 3671, 2871, 2115,
       1136, 2081])

In [209]:
find_unseen_movies_by_user_rating(2)

,MovieID,Rating,Title,Genres,Year
0,1,4.146846,Toy Story,Animation|Children's|Comedy,1995
16,17,4.027545,Sense and Sensibility,Drama|Romance,1995
46,47,4.106420,Seven (Se7en),Crime|Thriller,1995
49,50,4.517106,"Usual Suspects, The",Crime|Thriller,1995
56,58,4.093812,"Postino, Il (The Postman)",Drama|Romance,1994
...,...,...,...,...,...
3393,3634,4.254545,Seven Days in May,Thriller,1964
3429,3671,4.047364,Blazing Saddles,Comedy|Western,1974
3441,3683,4.218153,Blood Simple,Drama|Film-Noir,1984
3546,3789,4.198718,"Pawnbroker, The",Drama,1965
3568,3811,4.102778,Breaker Morant,Drama|War,1980

In [210]:
find_unseen_movies_by_user_rating(1)

,MovieID,Rating,Title,Genres,Year
28,29,4.062035,"City of Lost Children, The",Adventure|Sci-Fi,1995
46,47,4.106420,Seven (Se7en),Crime|Thriller,1995
106,110,4.234957,Braveheart,Action|Drama|War,1995
239,246,4.188547,Hoop Dreams,Documentary,1994
287,296,4.278213,Pulp Fiction,Crime|Drama,1994
309,318,4.554558,"Shawshank Redemption, The",Drama,1994
346,356,4.087967,Forrest Gump,Comedy|Romance|War,1994
432,446,4.082677,Farewell My Concubine,Drama|Romance,1993
443,457,4.103258,"Fugitive, The",Action|Thriller,1993
579,593,4.351823,"Silence of the Lambs, The",Drama|Thriller,1991
704,741,4.089172,Ghost in the Shell (Kokaku kidotai),Animation|Sci-Fi,1995
843,904,4.476190,Rear Window,Mystery|Thriller,1954
849,910,4.300481,Some Like It Hot,Comedy|Crime,1959
851,912,4.412822,Casablanca,Drama|Romance|War,1942
855,916,4.216471,Roman Holiday,Comedy|Romance,1953
862,923,4.388889,Citizen Kane,Drama,1941
931,994,4.095556,Big Night,Drama,1996
971,1036,4.121849,Die Hard,Action|Thriller,1988
1059,1136,4.335210,Monty Python and the Holy Grail,Comedy,1974
1066,1148,4.507937,"Wrong Trousers, The",Animation|Comedy,1993
1108,1198,4.477725,Raiders of the Lost Ark,Action|Adventure,1981
1111,1201,4.133820,"Good, The Bad and The Ugly, The",Action|Western,1966
1120,1210,4.022893,Star Wars: Episode VI - Return of the Jedi,Action|Adventure|Romance|Sci-Fi|War,1983
1123,1213,4.275196,GoodFellas,Crime|Drama,1990
1129,1219,4.218527,Psycho,Horror|Thriller,1960
1131,1221,4.357565,"Godfather: Part II, The",Action|Crime|Drama,1974
1133,1223,4.361522,"Grand Day Out, A",Animation|Comedy,1992
1135,1225,4.251809,Amadeus,Drama,1984
1139,1230,4.141679,Annie Hall,Comedy|Romance,1977
1143,1234,4.320305,"Sting, The",Comedy|Crime,1973
1148,1240,4.152050,"Terminator, The",Action|Sci-Fi|Thriller,1984
1166,1258,4.104876,"Shining, The",Horror,1980
1167,1259,4.096919,Stand by Me,Adventure|Comedy|Drama,1986
1174,1266,4.090271,Unforgiven,Western,1992
1188,1280,4.173285,Raise the Red Lantern,Drama,1991
1288,1387,4.089570,Jaws,Action|Horror,1975
1414,1537,4.137143,Shall We Dance? (Shall We Dansu?),Comedy,1996
1485,1617,4.219406,L.A. Confidential,Crime|Film-Noir|Mystery|Thriller,1997
1563,1704,4.176357,Good Will Hunting,Drama,1997
1886,2067,4.065603,Doctor Zhivago,Drama|Romance|War,1965
2058,2248,4.017505,Say Anything...,Comedy|Drama|Romance,1989
2131,2324,4.329861,Life Is Beautiful (La Vita è bella),Comedy|Drama,1997
2203,2396,4.127480,Shakespeare in Love,Comedy|Romance,1998
2374,2571,4.315830,"Matrix, The",Action|Sci-Fi|Thriller,1999
2651,2858,4.317386,American Beauty,Comedy|Drama,1999
2748,2959,4.077188,Fight Club,Drama,1999
2785,2997,4.125390,Being John Malkovich,Comedy,1999
2788,3000,4.147826,"Princess Mononoke, The (Mononoke Hime)",Action|Adventure|Animation,1997
3189,3421,4.053024,Animal House,Comedy,1978
3341,3578,4.106029,Gladiator,Action|Drama,2000

In [211]:
mean_rating = ratings.groupby('MovieID', as_index=False)[['Rating']].mean()

In [227]:
mean_rating

      MovieID    Rating
0           1  4.146846
1           2  3.201141
2           3  3.016736
3           4  2.729412
4           5  3.006757
...       ...       ...
3701     3948  3.635731
3702     3949  4.115132
3703     3950  3.666667
3704     3951  3.900000
3705     3952  3.780928

[3706 rows x 2 columns]